language: python
install:
- pip install nose requests requests-mock
script: "./gradlew build -PtestRunner=nosetests"
notifications:
  hipchat:
    rooms:
      secure: G0+KM106bV/J6RSsrubIUliDG3b9Z6qMI8JdQu5dghPwAzP7fP3oHrw+PLOjeLkZKsztf+Yns/qqfMVMHskb9g8hEYlHS1pg1aV0BNagNXckECUDY4OdwsORU0nNdQCnPQuopKfE+xPmDssr/v7BSHLDyWA24PoIb0KVUG7/fjQzyivy+eZ+BPUlatL/BeVVAekvvaz+HjCkSZJZfgH98W+/kpkOC5JKIavGGhwibMx/fPX5EVXFiZvkQHzksWOb8YB7qhgtU76sxISt89sJsqvzSCljSSPLdC0Pziyb0/TY7wR6rwuGoV/Bee/N47WGWK1jfaqNGeCPI0D1ZYZFiKKetZiCMPAy3pkq9gtIlw8srM2Va/xtYRuY/TlRpC+9e+pLt+4VYd/XCajkJpeUGUWnSxy+hc/NlsWMuoYiVGUB0XHaaMmqQY9Yy424RO2YFA0eorJ7MJY2imLYYfAI7zvgDo24Tfa1fwdFcXYsDyKncfRgSEXWR6AH/c0waJb4xfuKRwGrcYjyLw1UMsDuQpi2vl43CkIK2UsIR6oWq04Cflrd46gC0bzWc4/3WEFt9ItObQHb/Y5EgVAZ/n/bjj8QzhfMEXtkwPxWmQjb6+4L9qwv7ZYQ9Z4ovoEsFTR0Bn7n37CxnH6XCwKiEWJqR43Sp8H6d6FCUL5GDzp/vp4=
deploy:
  provider: releases
  api_key:
    secure: tNtkH2I+fLwWmgDl+Hs6XdJQy2gczgc+USWx2W7MuMxnL5HHIuLk/QR9lzZRmS6lfiZmTmB3pc4JoSkGMHHQ4rBBfVGaMBEjXQJFIKYsZV2oLMi2sJJSwwapsl4A5kD8UrVFApA+JONaByyvDxS87CtjjiC/ly3OG2jBwZIccYJx9FnhYajbPDJhnXENT5pEbqNYmzhwIhJwd0TojmdZeEmSE5oVYpZeCG/iXszP9nfecoxKcIzMb4I14N6JbDYEPgLSGT5cNZes3CMuDZP5Ta6aiVhj041BVy6m6GesCbjaWfbqcgm97UZGpm5EAm+Ke2y18r30ZvyYfFCi2aTWDke3mlAW901oaEjSdWHXJZi7Xhhihv8jXQqhqTt1DUEt7QRn8Qz3Kv6RFiMt0CuhVsF9VxBInN8xCUAIVWYCzzKlkO6bFxOmkMeVNtQo0HWsgX2VXyNpzyloJRcPfY0wm1HcUWS2kjMpq2PVxUyBRGorfpWGsTj0aZX9kOjVO2Hg6P5TBoiRLT2gRR2ATxEtS4obSpahO/LwaKbMhrFFRfPr/vLPC7JfwLPK4euXFIiCmbwil1MDnkH5qVrhMEBWzN32+AcK8GeCcLqDXfQT4SeWfYNS8/FwN+A/ZYLM4/+WJSqs62HEhuaxhIYHt+5zzoQ37MwsuV5Dt4Yo07CsCCc=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_bracnhes: true
    tags: true
    repo: xebialabs-community/xlr-sdelements-plugin
