language: python
install:
- pip install nose requests requests-mock
script: "./gradlew build -PtestRunner=nosetests"
notifications:
  slack:
    secure: kAI70VDS5B/9oy4wyTd736df6afJare/BYpVxs0kkPfdz4vl5zZzGocgheBz5kTVgx1c6WFXmN6cju915WJkMnmQogfMe0LXetsi+OoNlEGkKvmGCREwgWVCIP1tZvwCCrop2Gz1h1S1Btsmxnrx0zF3InAq5N2hd8knveQP/sO9IyLN49KBcvbVa3KJEvB86k8Q+jvin29feALr7ypcx7auqksP7FvTx2SYLD1WOW4NqQZFpfMHT2nKg80l4FD+UnWTi7f5zs6LjC8L128ClH7KxyPWoVEqR8/CsvHVyvSoMXLw/PB5LMpq/9azj9kJAb3P5RZsuSTE715MABFhA4A+YpsHp2znPCVSGYi9gfKpNjnv4yCCmkMv9XYGTVeZsbecB2832m0ispcu4azEk46od1TVP3Nr9+JC6z6zlptEDOyKG5SJ/AuPVWFuarGS8907doE/Qj+HW+flEDfku/r+l4hodeFCbPIlP0FRdKt13oiyB87BCh8Yn7/pvGL2MuLtz7GiRHOu/bWp/bKJ1TyrYUFGVghxqLmCCvViWx7DFWHf3FB1DjsmpbUl/gp7AdWBQoUYK7aXHJ4MWMZNQ+Fndcu3hqGc4OoF+1SOa+CFjfHXS5oaiaNfaoN/U3n9tAQOGYH4rkpytMym7KWhQ/I46wg/qpNDtv5WBYVsCJ0=
deploy:
  provider: releases
  api_key:
    secure: tNtkH2I+fLwWmgDl+Hs6XdJQy2gczgc+USWx2W7MuMxnL5HHIuLk/QR9lzZRmS6lfiZmTmB3pc4JoSkGMHHQ4rBBfVGaMBEjXQJFIKYsZV2oLMi2sJJSwwapsl4A5kD8UrVFApA+JONaByyvDxS87CtjjiC/ly3OG2jBwZIccYJx9FnhYajbPDJhnXENT5pEbqNYmzhwIhJwd0TojmdZeEmSE5oVYpZeCG/iXszP9nfecoxKcIzMb4I14N6JbDYEPgLSGT5cNZes3CMuDZP5Ta6aiVhj041BVy6m6GesCbjaWfbqcgm97UZGpm5EAm+Ke2y18r30ZvyYfFCi2aTWDke3mlAW901oaEjSdWHXJZi7Xhhihv8jXQqhqTt1DUEt7QRn8Qz3Kv6RFiMt0CuhVsF9VxBInN8xCUAIVWYCzzKlkO6bFxOmkMeVNtQo0HWsgX2VXyNpzyloJRcPfY0wm1HcUWS2kjMpq2PVxUyBRGorfpWGsTj0aZX9kOjVO2Hg6P5TBoiRLT2gRR2ATxEtS4obSpahO/LwaKbMhrFFRfPr/vLPC7JfwLPK4euXFIiCmbwil1MDnkH5qVrhMEBWzN32+AcK8GeCcLqDXfQT4SeWfYNS8/FwN+A/ZYLM4/+WJSqs62HEhuaxhIYHt+5zzoQ37MwsuV5Dt4Yo07CsCCc=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_bracnhes: true
    tags: true
    repo: xebialabs-community/xlr-sdelements-plugin
